### PR TITLE
Changed createGitRepository within git tests

### PR DESCRIPTION
**Pull request by oatmealraisin**
This makes sure that the Git commands are tested agains a valid Git
repository.

@php-coder @bparees ptal?

### CODE REVIEW

**Comment by oatmealraisin** [comment]
This should fix the bump issue -- it does locally at least :)

**Comment by bparees** [comment]
@oatmealraisin thought you were going to make this a utility method instead of repeating it?

**Comment by oatmealraisin** [comment]
@bparees Sorry, I assumed that I shouldn't piggyback it on another commit, it's going to be a part of both s2i and origin

**Comment by bparees** [comment]
> Sorry, I assumed that I shouldn't piggyback it on another commit, it's going to be a part of both s2i and origin

you mean the utility method will be defined in s2i and then this code will be updated to use it?

**Comment by oatmealraisin** [comment]
@bparees Yes thanks, that's what I meant.

**Comment by php-coder** [comment]
I've applied you commit manually. Thanks!

**Pull request closed without merging**
